[env]
TERM = "xterm-256color"

decorations = "Buttonless"

[colors.bright]
black = "#32344a"
blue = "#4b4e6f"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#f7768e"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#32344a"
blue = "#59969c"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#4bebad"
red = "#f7768e"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.primary]
background = "#262a32"
foreground = "#d8dee8"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100

[window]
opacity = 0.92
blur = true

[window.padding]
x = 15
y = 15
